steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cymbal-repo/mcp-server', '-f', 'Dockerfile.mcp', '.']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cymbal-repo/mcp-server'

